\documentclass{article}

\begin{document}

\begin{figure}
\begin{minipage}[t]{0.48\linewidth}
<<fVSmTimeA, echo=FALSE, w=2.85, h=3.0, out.width="\\textwidth">>=
@ %
\end{minipage} 
\hspace*{0.02\linewidth}
\begin{minipage}[t]{0.48\linewidth}
<<fVSmTimeB, echo=FALSE, w=2.85, h=2.5, out.width="\\textwidth">>=
@ %
\end{minipage} 
  \caption{Graphs compare female with male record times,
  for Northern Ireland hill races.  Least squares lines
    are added, and marginal boxplots are shown on the
    horizontal axis. Panel A
    has untransformed scales, while Panel B has log
    transformed scales.}\label{fig:nimff}
% \setfloatalignment{t}% forces caption to be top-aligned
\end{figure}



\end{document}